[package]
name = "blockgame-client"
version = "0.1.0"
authors = ["Layl <LaylConway@users.noreply.github.com>"]

[dependencies]
ggez = "0.4"
gfx = "0.17"
gfx_device_gl = "0.15"
nalgebra = { version = "0.14", features = ["serde-serialize"] }
slog = "2"
sloggers = "0.2"
